nilai = {3,6,9,2,5,7}
nilai.add(1)
nilai.add(2)
nilai.update({4,8,9,10})
print(nilai)
nilai.discard(1)
nilai.discard(3)
nilai.discard(4)
nilai.discard(5)
nilai.discard(7)
nilai.discard(8)
nilai.discard(10)
print(nilai)
